# Generated by Django 3.1.3 on 2022-01-24 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantes',
            name='celular',
        ),
        migrations.AddField(
            model_name='participantes',
            name='fecha_actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='participantes',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
