# Generated by Django 3.1.3 on 2022-01-24 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0002_auto_20220124_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='celular',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
