# Generated by Django 3.1.3 on 2022-01-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0004_remove_participantes_fecha_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='fecha_actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
