# Generated by Django 3.1.3 on 2022-01-24 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0005_auto_20220124_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantes',
            name='cel',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantes',
            name='fecha_actualizado',
            field=models.DateField(auto_now=True),
        ),
    ]
