# Generated by Django 3.1.3 on 2022-01-24 22:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0006_auto_20220124_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantes',
            name='cel',
        ),
        migrations.AddField(
            model_name='participantes',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantes',
            name='fecha_actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
