# Generated by Django 3.1.3 on 2022-01-24 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0007_auto_20220124_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantes',
            name='fecha_creado',
        ),
    ]
