# Generated by Django 3.1.3 on 2022-01-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0008_remove_participantes_fecha_creado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participantes',
            name='fecha_actualizado',
        ),
    ]
